function fillLiterals(){
    // 直接使用中文文本，不再从语言文件加载
    const chineseTexts = {
      "litTitle": "高亮资源关键字AI破解魔改自定义悬浮备注版V3",
      "popup_title": "Highlight This!",
      "byline": "让网页查找资源更醒目",
      "popup_nowords": "还没有定义关键字列表",
      "collapseAll": "全部折叠",
      "popup_create1": "创建一个关键字列表，让 ",
      "popup_create2": " 在浏览网页时自动检测并高亮显示它们。",
      "toConfig": "< 返回配置关键字",
      "foundWords": "我们在此页面上找到了这些关键字。",
      "dontShowWordsLabel": "不再显示页面上找到的关键字",
      "field_listname": "列表名称：",
      "field_colors": "颜色：",
      "field_colors_help": "选择颜色或输入 HTML 颜色代码，例如 \"#ccc\" 或 \"green\"",
      "field_foreground": "前景色",
      "field_background": "背景色",
      "field_boxColor": "输入框边框颜色",
      "example1": "这是一个",
      "example2": "高亮文本的",
      "example": "示例",
      "field_detection_help": "仅检测完整关键字",
      "field_words": "关键字：",
      "sites_info": "列出您希望高亮显示的网站。您可以定义白名单和黑名单。黑名单优先。如果未定义任何内容，则在所有页面上设置高亮。您可以使用 * 和 ? 等通配符。<br /> 示例：*.google.com, www.google.com, www.google.com/something/page.html, www.go?gle.com/*/page.html",
      "field_highlightOn": "在以下网站高亮",
      "field_dontHighlight": "不在以下网站高亮：",
      "cancelAddGroup": "取消",
      "popup_settings": "设置",
      "field_showFoundWords": "显示找到的关键字：",
      "field_printHighlights": "打印高亮：",
      "field_neverHighlightOn": "永不在以下网站高亮：",
      "field_neverHighlightOn_help": "<br />列出您永远不希望出现高亮的网站。您可以使用 * 和 ? 等通配符。<br /> 示例：*.google.com, www.google.com, www.google.com/something/page.html",
      "cancelSettings": "取消",
      "saveSettings": "保存",
      "field_exportSettings": "导出设置：",
      "exportLink": "导出",
      "field_importSettings": "导入设置：",
      "importFileLink": "导入",
      "restoreWarning": "恢复备份",
      "popup_confirmDelete": "您确定要删除该关键字列表及其关键字吗？",
      "yesDeleteGroup": "是",
      "noDeleteGroup": "否",
      "labelListName": "列表名称",
      "newGroupTitle": "您想在哪里管理关键字？",
      "newGroupDetail": "您可以在 Highlight This 中管理关键字列表，也可以在 Highlight This 外部（例如 pastebin）管理它们并定期导入。",
      "cancelCreateGroup": "取消",
      "createGroupLink": "下一步",
      "localLabel": "本地",
      "remoteLabel": "远程",
      "field_source": "来源：",
      "field_useRegexTokens_help": "使用正则表达式标记而不是简单的 * 和 ? 通配符",
      "field_caseSensitive_label": "区分大小写比较",
      "syncLinkText": "同步",
      "field_performance": "性能",
      "performanceHelp": "定义 Highlight This 允许对您的设备资源（处理能力）产生多大影响。",
      "field_showInEditableFields_help": "在可编辑字段中高亮",
      "field_notifyOnHighlight_help": "找到关键字时通知",
      "notifyFrequency_1": "每页一次",
      "notifyFrequency_2": "每次",
      "newGroupTitleStorage": "您想在浏览器之间同步此列表吗？",
      "newGroupDetailStorage": "同步列表在您登录浏览器后可在所有浏览器中使用，但由于存储限制，它支持的关键字较少。",
      "storageLocalLabel": "否，不同步此列表",
      "storageSyncLabel": "是，同步此列表",
      "non_unicode_chars": "您已将非 Unicode 字符添加到关键字列表中，取消选中完整关键字检测以正确高亮显示它们",
      "tabGeneral": "常规",
      "tabStyleScreen": "样式",
      "tabLimitations": "限制",
      "tabSettingsLimitations": "限制",
      "tabAdvanced": "高级",
      "tabAction": "动作",
      "tabSettingsGeneral": "常规",
      "tabSettingsBackup": "备份",
      "titleCreateNewList": "创建新列表",
      "remotelist_help": "远程来源需要返回一个文本文件，其中关键字位于单独的行上，类似于您创建本地列表的方式。",
      "wordsMoveMenuTitle": "移动到：",
      "action_intro": "定义点击高亮时要执行的操作",
      "label_link": "链接：",
      "action_none": "无",
      "action_newtab": "在新标签页中打开",
      "actionExampleHelp": "例如，使用标记 \"Hi?hL*\" 高亮单词 \"highlight\"，将产生：",
      "action_tip1": "<strong>%t%</strong> 被替换为页面上找到的文本（例如 Highlight）",
      "action_tip2": "<strong>%s%</strong> 被替换为您的搜索关键字（例如 Hi?hL*）",
      "action_tip3": "<strong>%tu%</strong> 或 <strong>%tl%</strong>，<strong>%su%</strong> 或 <strong>%sl%</strong> 强制转换为大写或小写",
      "action_tip4": "一些示例：https://wikipedia.com/%t% , https://google.com/search?q=%t%",
      "last_synced_on": "上次同步时间：",
      "launchGoogleSheetsAssisantbtn": "启动助手",
      "closeGoogleSheetsAssisantbtn": "关闭助手",
      "labelSheetsId": "Sheets ID：",
      "googleSheetsAssistantTitle": "Google Sheets 助手",
      "googleAssist1": "创建或打开现有的 Google Sheets 文档。",
      "googleAssist2": "在第一个工作表的第一列中创建您的关键字列表。",
      "googleAssist3": "在网络上发布您的工作表",
      "googleAssist4": "共享 Google Sheets",
      "googleAssist5": "从\"复制链接\"中选择链接",
      "googleAssist6": "在此处粘贴链接",
      "menu_home_label": "主页",
      "menu_settings_label": "设置",
      "menu_subscription_label": "订阅",
      "menu_help_label": "帮助",
      "field_words_help": "您可以使用 * 和 ? 通配符，每一行被视为一个关键字",
      "changelicense-ad-moreinfo": "更多信息",
      "field_containerSelector": "仅当容器匹配此查询选择器时才高亮",
      "field_clearSyncLists": "重置数据和设置：",
      "info_clearSyncLists": "在重置数据和设置之前，请确保创建备份",
      "resetDataAndSettings": "重置数据和设置",
      "popup_confirmReset": "<div>您确定要重置所有数据和设置吗？</div><div>在继续之前请确保已备份</div>",
      "yesReset": "重置所有数据",
      "noReset": "取消",
      "field_sendErrors": "向开发者报告错误",
      "field_magicHighlighting": "更快的高亮",
      "sendErrorsHelp": "<p>如果您遇到问题，请向开发者发送错误报告。</p><p>捕获的错误也将被发送，此信息不包含个人数据或关键字。</p>",
      "field_sendErrorsDescription": "问题描述：",
      "field_sendErrorsEmail": "电子邮件地址：",
      "sendErrorsButton": "发送",
      "menu_sendErrors_label": "报告错误",
      "field_autoBackupSettings": "自动备份：",
      "info_autoBackupSettings": "在您的下载文件夹中创建备份",
      "autoBackup_Never": "从不",
      "autoBackup_Daily": "每天",
      "autoBackup_Weekly": "每周",
      "autoBackup_Monthly": "每月",
      "action_sametab": "在当前标签页中打开"
    };

    for (label in chineseTexts){
      const element = document.getElementById(label);
      if (element) {
        element.innerHTML = chineseTexts[label];
      }
    }

    const placeholderAssignments={
      "filterwords": "filterwords",
      "filterwordlist": "filterwords" 
    }
    for (label in placeholderAssignments){
      document.getElementById(label).placeholder = chrome.i18n.getMessage(placeholderAssignments[label]);
    }
}

function getLiteral(literal) {
  //return 'yyy';
  return chrome.i18n.getMessage(literal);
}

